import AppKit
import Carbon.HIToolbox

private func snippetKeywordCallback(
    proxy: CGEventTapProxy, type: CGEventType, event: CGEvent,
    userInfo: UnsafeMutableRawPointer?
) -> Unmanaged<CGEvent>? {
    guard let userInfo else { return Unmanaged.passUnretained(event) }
    let listener = Unmanaged<SnippetKeywordListener>.fromOpaque(userInfo).takeUnretainedValue()

    if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
        DispatchQueue.main.async { listener.reenable() }
        return Unmanaged.passUnretained(event)
    }

    // 1. Ignore synthetic events generated by Tinycast to avoid event loops
    let sourceTag = event.getIntegerValueField(.eventSourceUserData)
    if sourceTag == Paster.tinycastEventTag {
        return Unmanaged.passUnretained(event)
    }

    // 2. Security Guard: Privacy protection when secure password input is enabled
    if IsSecureEventInputEnabled() {
        DispatchQueue.main.async { listener.clearBuffer() }
        return Unmanaged.passUnretained(event)
    }

    guard type == .keyDown else { return Unmanaged.passUnretained(event) }

    let flagsRaw = event.flags.rawValue
    let keyCode = UInt16(event.getIntegerValueField(.keyboardEventKeycode))

    var length = 0
    var chars = [UniChar](repeating: 0, count: 4)
    event.keyboardGetUnicodeString(maxStringLength: 4, actualStringLength: &length, unicodeString: &chars)
    let char = length > 0 ? String(utf16CodeUnits: chars, count: length) : nil

    DispatchQueue.main.async {
        listener.processKeyDown(keyCode: keyCode, flagsRaw: flagsRaw, char: char)
    }

    return Unmanaged.passUnretained(event)
}

@MainActor
final class SnippetKeywordListener {
    nonisolated(unsafe) private var eventTap: CFMachPort?
    nonisolated(unsafe) private var runLoopSource: CFRunLoopSource?
    private var healthTimer: Timer?
    private var isTapStarting: Bool = false
    private var isExpanding: Bool = false
    private var keyBuffer: String = ""
    private var lastKeystrokeTime: Date = Date()
    private var appSwitchObserver: NSObjectProtocol?
    private weak var store: SnippetsStore?
    private var onArgumentPrompt: ((Snippet, [String]) -> Void)?

    init(store: SnippetsStore) {
        self.store = store
        setupAppSwitchObserver()
    }

    func start(onArgumentPrompt: @escaping (Snippet, [String]) -> Void) {
        self.onArgumentPrompt = onArgumentPrompt
        setupEventTap()
        startHealthTimer()
    }

    func stop() {
        if let appSwitchObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(appSwitchObserver)
            self.appSwitchObserver = nil
        }

        healthTimer?.invalidate()
        healthTimer = nil

        if let runLoopSource {
            CFRunLoopRemoveSource(CFRunLoopGetMain(), runLoopSource, .commonModes)
        }
        if let eventTap {
            CGEvent.tapEnable(tap: eventTap, enable: false)
            CFMachPortInvalidate(eventTap)
        }
        eventTap = nil
        runLoopSource = nil
    }

    func clearBuffer() {
        keyBuffer.removeAll()
    }

    private func setupAppSwitchObserver() {
        appSwitchObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.clearBuffer()
            }
        }
    }

    private func startHealthTimer() {
        guard healthTimer == nil else { return }
        healthTimer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.healthCheck()
            }
        }
    }

    private func healthCheck() {
        if eventTap == nil {
            setupEventTap()
        }
    }

    fileprivate nonisolated func reenable() {
        if let eventTap {
            CGEvent.tapEnable(tap: eventTap, enable: true)
        }
    }

    private func setupEventTap() {
        guard eventTap == nil && !isTapStarting else { return }
        if !Permissions.isInputMonitoringTrusted() {
            Permissions.requestInputMonitoringPrompt()
        }
        guard Permissions.isAccessibilityTrusted() else { return }

        isTapStarting = true
        let thread = EventTapThread(listener: self)
        thread.start()
    }

    fileprivate nonisolated func setupTapInThread() {
        let mask = (1 << CGEventType.keyDown.rawValue)
        let observer = Unmanaged.passUnretained(self).toOpaque()

        guard let tap = CGEvent.tapCreate(
            tap: .cgAnnotatedSessionEventTap,
            place: .headInsertEventTap,
            options: .listenOnly,
            eventsOfInterest: CGEventMask(mask),
            callback: snippetKeywordCallback,
            userInfo: observer
        ) else {
            NSLog("Tinycast: Failed to create CGEvent tap")
            return
        }

        self.eventTap = tap
        let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0)
        self.runLoopSource = source
        if let source {
            CFRunLoopAddSource(CFRunLoopGetCurrent(), source, .commonModes)
        }
        CGEvent.tapEnable(tap: tap, enable: true)
        CFRunLoopRun()
    }
    fileprivate func processKeyDown(keyCode: UInt16, flagsRaw: UInt64, char: String?) {
        let now = Date()
        // Reset buffer if more than 15 seconds of typing inactivity
        if now.timeIntervalSince(lastKeystrokeTime) > 15.0 {
            keyBuffer.removeAll()
        }
        lastKeystrokeTime = now

        let flags = CGEventFlags(rawValue: flagsRaw)

        // Ignore modifier shortcut combos (⌘ or ⌃ pressed)
        if flags.contains(.maskCommand) || flags.contains(.maskControl) {
            keyBuffer.removeAll()
            return
        }

        // Reset buffer on special navigation/delimiter keys
        if keyCode == kVK_Return || keyCode == kVK_Escape || keyCode == kVK_Tab ||
           keyCode == kVK_LeftArrow || keyCode == kVK_RightArrow || keyCode == kVK_UpArrow || keyCode == kVK_DownArrow {
            keyBuffer.removeAll()
            return
        }

        // Handle Backspace
        if keyCode == kVK_Delete {
            if !keyBuffer.isEmpty { keyBuffer.removeLast() }
            return
        }

        // Convert keycode to string character
        if let char {
            keyBuffer.append(char)
            if keyBuffer.count > 50 {
                keyBuffer.removeFirst(keyBuffer.count - 50)
            }

            // Check for matching keywords (case-insensitive)
            if let store = self.store {
                let activeSnippets = store.snippets.filter { $0.isEnabled && $0.keyword != nil && !$0.keyword!.isEmpty }
                let lowerBuffer = keyBuffer.lowercased()
                for snippet in activeSnippets {
                    if let kw = snippet.keyword, lowerBuffer.hasSuffix(kw.lowercased()) {
                        keyBuffer.removeAll()
                        triggerSnippetExpansion(snippet: snippet, keywordLength: kw.count)
                        break
                    }
                }
            }
        }
    }

    private func triggerSnippetExpansion(snippet: Snippet, keywordLength: Int) {
        guard let store, !isExpanding else { return }
        isExpanding = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.4) { [weak self] in
            self?.isExpanding = false
        }

        let frontApp = NSWorkspace.shared.frontmostApplication

        // 1. Send backspaces with 8ms pacing to erase the typed keyword cleanly in any application
        self.simulateBackspaces(count: keywordLength)

        // 2. Expand template
        let result = SnippetTemplateEngine.expand(snippet, snippets: store.snippets)

        // 3. If missing arguments, request input prompt
        if !result.missingArguments.isEmpty {
            self.onArgumentPrompt?(snippet, result.missingArguments)
            return
        }

        // 4. Inject after backspaces finish processing
        let injectionDelay = Double(keywordLength) * 0.008 + 0.05
        DispatchQueue.main.asyncAfter(deadline: .now() + injectionDelay) {
            Paster.injectString(result.text, previousApp: frontApp)

            // 5. Position cursor if {cursor} offset was present
            if let offset = result.cursorOffsetFromEnd, offset > 0 {
                let cursorDelay = 0.08
                DispatchQueue.main.asyncAfter(deadline: .now() + cursorDelay) {
                    self.simulateLeftArrows(count: offset)
                }
            }
        }
    }

    private func simulateBackspaces(count: Int) {
        let source = CGEventSource(stateID: .combinedSessionState)
        for i in 0..<count {
            DispatchQueue.main.asyncAfter(deadline: .now() + Double(i) * 0.008) {
                guard let down = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_Delete), keyDown: true),
                      let up = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_Delete), keyDown: false) else { return }
                down.setIntegerValueField(.eventSourceUserData, value: Paster.tinycastEventTag)
                up.setIntegerValueField(.eventSourceUserData, value: Paster.tinycastEventTag)

                down.post(tap: .cghidEventTap)
                up.post(tap: .cghidEventTap)
            }
        }
    }

    private func simulateLeftArrows(count: Int) {
        let source = CGEventSource(stateID: .combinedSessionState)
        for i in 0..<count {
            DispatchQueue.main.asyncAfter(deadline: .now() + Double(i) * 0.008) {
                guard let down = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_LeftArrow), keyDown: true),
                      let up = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_LeftArrow), keyDown: false) else { return }
                down.setIntegerValueField(.eventSourceUserData, value: Paster.tinycastEventTag)
                up.setIntegerValueField(.eventSourceUserData, value: Paster.tinycastEventTag)

                down.post(tap: .cghidEventTap)
                up.post(tap: .cghidEventTap)
            }
        }
    }
}

private final class EventTapThread: Thread, @unchecked Sendable {
    private weak var listener: SnippetKeywordListener?

    init(listener: SnippetKeywordListener) {
        self.listener = listener
        super.init()
        self.name = "com.tinycast.eventtap"
        self.qualityOfService = .userInteractive
    }

    override func main() {
        guard let listener else { return }
        listener.setupTapInThread()
    }
}
